VS-17 general changes
kosta232mentorweb/chehov pull request #84
Opened 2023-02-07 20:13 UTC by ArtemYunkevich

2023-02-08 10:49 UTC, kosta232mentorweb requested changes

2023-02-08 10:49 UTC, kosta232mentorweb commented on html/VS-17.html
> +<!DOCTYPE html>ОБ
ЧТо это тут затесалось?

2023-02-08 16:58 UTC, ArtemYunkevich commented on html/VS-17.html
> +<!DOCTYPE html>ОБ
Исправления внесены

2023-02-09 05:32 UTC, kosta232mentorweb approved these changes

2023-02-09 05:32 UTC, kosta232mentorweb commented on html/VS-17.html
> +<!DOCTYPE html>ОБ
неа

2023-02-09 05:32 UTC, merged